const SET_FIRST_SCREEN_DATA = 'SET_FIRST_SCREEN_DATA';
const SET_SECOND_SCREEN_DATA = 'SET_SECOND_SCREEN_DATA';
const SET_THIRD_SCREEN_DATA = 'SET_THIRD_SCREEN_DATA';
const SET_FOURTH_SCREEN_DATA = 'SET_FOURTH_SCREEN_DATA';


export {
    SET_FIRST_SCREEN_DATA,
    SET_SECOND_SCREEN_DATA,
    SET_THIRD_SCREEN_DATA,
    SET_FOURTH_SCREEN_DATA
}